packages:
  - 'packages/*'
catalogs:
  default:
    '@types/node': 20.19.43
    '@types/parse-gitignore': 1.0.2
    eslint: 10.6.0
    tsdown: 0.22.3
    typescript: 6.0.3
    vite: 8.1.0
    vitest: 4.1.9
allowBuilds:
  es5-ext: true
