# https://fotoallerlei.com/blog/post/2020/automatic-dependency-updates-with-renovate-and-gitlab/post
.renovate:
  variables:
    RENOVATE_GIT_AUTHOR: '${GITLAB_USER_NAME} <${GITLAB_USER_EMAIL}>'
    RENOVATE_DRY_RUN: 'false'
    RENOVATE_LOG_LEVEL: debug
    RENOVATE_ALLOWED_POST_UPGRADE: '^pod ,^pnpm,^npm ,^yarn '
    # RENOVATE_DISABLED: "🛑"
  rules:
    - if: $RENOVATE_DISABLED
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never
  image:
    name: renovate/renovate@sha256:4cd17e16873f200370add2d4f790b3db7406ca16ca904f5d29ac0d13e5c726fb
    entrypoint: ['']
  script:
    - >
      renovate
      --platform "gitlab"
      --endpoint "${CI_API_V4_URL}"
      --git-author "${RENOVATE_GIT_AUTHOR}"
      --dry-run "${RENOVATE_DRY_RUN}"
      --log-file-level "${RENOVATE_LOG_LEVEL}"
      --allow-post-upgrade-command-templating
      --allowed-post-upgrade-commands "${RENOVATE_ALLOWED_POST_UPGRADE}"
      "${CI_PROJECT_PATH}"
  tags:
    - renovate
