const path = require('node:path');
const { file } = require('mrm-core');

function task() {
  // code of conduct
  const EOL = '\n';
  const codeOfConduct = 'CODE_OF_CONDUCT.md';
  const codeOfConductFile = file(codeOfConduct);
  if (!codeOfConductFile.exists() || !codeOfConductFile.get().includes(`<!-- EditMode: MANUAL -->`)) {
    const codeOfConductTemplate = file(path.join(__dirname, 'templates', codeOfConduct)).get();
    codeOfConductFile.save(
      [
        `<!--
Generated by mrm
  * change EditMode: MANUAL to avoid overwriting by mrm
-->`,
        `<!-- EditMode: AUTO -->`,
        codeOfConductTemplate,
      ].join(EOL)
    );
  }
}

task.description = 'Setup Contributing';
task.parameters = {};
module.exports = task;
