name: CI
on:
  merge_group: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  code-quality: write
  contents: read
  packages: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: ⚙️ Setup
        uses: w5s/actions/setup@0c11193917dd93bfbf8bb107fcf557f10f93b0e3 # main
      - name: 🔨 Build
        uses: w5s/actions/task@0c11193917dd93bfbf8bb107fcf557f10f93b0e3 # main
        with:
          task: build
      - name: 🔍 Validate
        uses: w5s/actions/task@0c11193917dd93bfbf8bb107fcf557f10f93b0e3 # main
        with:
          task: validate
