name: CI
on:
  merge_group: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: ⚙️ Setup
        uses: w5s/actions/setup@f43e3ab61de5e8f1471ed61d184fc5b67ab9c2af # main
      - name: 🔨 Build
        uses: w5s/actions/task@f43e3ab61de5e8f1471ed61d184fc5b67ab9c2af # main
        with:
          task: build
      - name: 🔍 Validate
        uses: w5s/actions/task@f43e3ab61de5e8f1471ed61d184fc5b67ab9c2af # main
        with:
          task: validate
