name: Node.js CI
on:
  merge_group:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install --immutable
      - run: yarn run build
      - run: yarn validate
